### ISSUE TITLE
8chan.co -> 8ch.net

### ISSUE THREAD

**Issue by Strat-** [j3lte/chanarchive#1]

**Comment by j3lte** [comment]
Thank you. I will update this in a couple of days, wouldn't take too long I guess.

**Comment by j3lte** [comment]
This is fixed in 4d7a0886c830de42b8d4f5fa0caa5d67de83d0c2 and published in npm under [0.4.3](https://github.com/j3lte/chanarchive/releases/tag/v0.4.3) :-)

**Comment by Strat-** [comment]
Thanks.
